name: Build OVMS Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: |
            vehicle/OVMS.V3/build
            ~/.ccache
          key: ovms-build-${{ runner.os }}-${{ hashFiles('vehicle/OVMS.V3/**', '!**/build/**') }}
          restore-keys: |
            ovms-build-${{ runner.os }}-

      - name: Build OVMS with upgraded CMake
        uses: addnab/docker-run-action@v3
        with:
          image: espressif/idf:release-v3.3
          options: -v ${{ github.workspace }}:/workspace
          shell: bash
          run: |
            set -e

            echo "🔸 Installing CMake 3.26.4..."
            wget -q https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-linux-x86_64.sh
            chmod +x cmake-3.26.4-linux-x86_64.sh
            ./cmake-3.26.4-linux-x86_64.sh --skip-license --prefix=/usr/local/cmake

            # Force the new cmake to the front of PATH
            export PATH="/usr/local/cmake/bin:$PATH"
            cmake --version

            echo "🔸 Installing ccache..."
            apt-get update -y
            apt-get install -y ccache

            cd /workspace/vehicle/OVMS.V3

            echo "🔸 Preparing sdkconfig..."
            if [ ! -f sdkconfig ]; then
              if [ -f sdkconfig.default ]; then
                cp sdkconfig.default sdkconfig
              fi
            fi

            echo "🔸 Sourcing ESP-IDF..."
            source ${IDF_PATH}/export.sh

            echo "🔸 Enabling ccache..."
            export IDF_CCACHE_ENABLE=1

            echo "🔸 Building firmware..."
            idf.py build

            echo "✅ Build complete"

      - name: Upload firmware artefacts
        uses: actions/upload-artifact@v4
        with:
          name: ovms-firmware
          path: |
            vehicle/OVMS.V3/build/ovms3.bin
            vehicle/OVMS.V3/build/bootloader/bootloader.bin
            vehicle/OVMS.V3/build/partition_table/partition-table.bin
            vehicle/OVMS.V3/build/ota_data_initial.bin
