name: Build OVMS Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build in Espressif container
        uses: addnab/docker-run-action@v3
        with:
          image: espressif/idf:release-v3.3
          options: -v ${{ github.workspace }}:/workspace
          shell: bash
          run: |
            set -e
            cd /workspace/vehicle/OVMS.V3

            echo "🔹 Preparing sdkconfig..."
            if [ ! -f sdkconfig ]; then
              cp sdkconfig.default sdkconfig
            fi

            echo "🔹 Sourcing ESP-IDF..."
            source ${IDF_PATH}/export.sh

            echo "🔹 Building firmware..."
            idf.py build

            echo "✅ Build finished"
      
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: ovms-firmware
          path: vehicle/OVMS.V3/build/ovms3.bin
