name: Build OVMS Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: |
            vehicle/OVMS.V3/build
            ~/.ccache
          key: ovms-build-${{ runner.os }}-${{ hashFiles('vehicle/OVMS.V3/**', '!**/build/**') }}
          restore-keys: |
            ovms-build-${{ runner.os }}-

      - name: Build OVMS with upgraded CMake
        uses: addnab/docker-run-action@v3
        with:
          image: espressif/idf:release-v3.3
          options: -v ${{ github.workspace }}:/workspace
          shell: bash
          run: |
            set -e
            apt-get update
            apt-get install -y wget software-properties-common lsb-release
            apt-get purge -y cmake
            wget -qO- https://apt.kitware.com/keys/kitware-archive-latest.asc | gpg --dearmor -o /usr/share/keyrings/kitware-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/kitware.list
            apt-get update
            apt-get install -y cmake ccache

            cd /workspace/vehicle/OVMS.V3

            echo "🔸 Preparing sdkconfig..."
            if [ ! -f sdkconfig ]; then
              if [ -f sdkconfig.default ]; then
                cp sdkconfig.default sdkconfig
              fi
            fi

            echo "🔸 Sourcing ESP-IDF..."
            source ${IDF_PATH}/export.sh

            echo "🔸 Enabling ccache..."
            export IDF_CCACHE_ENABLE=1

            echo "🔸 Building firmware..."
            idf.py build

            echo "✅ Build complete"

      - name: Upload firmware artefacts
        uses: actions/upload-artifact@v4
        with:
          name: ovms-firmware
          path: |
            vehicle/OVMS.V3/build/ovms3.bin
            vehicle/OVMS.V3/build/bootloader/bootloader.bin
            vehicle/OVMS.V3/build/partition_table/partition-table.bin
            vehicle/OVMS.V3/build/ota_data_initial.bin
