name: Build OVMS (ESP-IDF v3.3)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Run all steps inside the IDF v3.3 toolchain container
    container:
      image: espressif/idf:release-v3.3

    env:
      # We'll clone the OVMS ESP-IDF fork into the workspace and use that as IDF_PATH
      IDF_PATH: ${{ github.workspace }}/esp-idf
      CCACHE_DIR: /root/.ccache

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: /root/.ccache
          key: ovms-ccache-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('vehicle/OVMS.V3/**') }}
          restore-keys: |
            ovms-ccache-${{ runner.os }}-${{ github.ref_name }}-
            ovms-ccache-${{ runner.os }}-

      - name: Get OVMS ESP-IDF v3.3 fork
        run: |
          git clone https://github.com/openvehicles/esp-idf.git "$IDF_PATH"
          cd "$IDF_PATH"
          git submodule update --init --recursive

      - name: Prepare sdkconfig
        working-directory: vehicle/OVMS.V3
        run: |
          if [ ! -f sdkconfig ]; then
            # Match your Windows guide: use the HW31 default unless you keep a committed sdkconfig
            cp support/sdkconfig.default.hw31 sdkconfig
          fi

      - name: Build (make, parallel)
        working-directory: vehicle/OVMS.V3
        run: |
          echo "Using IDF_PATH=$IDF_PATH"
          make -j"$(nproc)" all

      - name: Upload firmware artefacts
        uses: actions/upload-artifact@v4
        with:
          name: ovms-firmware-${{ github.sha }}
          path: |
            vehicle/OVMS.V3/build/ovms3.bin
            vehicle/OVMS.V3/build/bootloader/bootloader.bin
            vehicle/OVMS.V3/build/partitions_*.bin
            vehicle/OVMS.V3/build/ota_data_initial.bin
            vehicle/OVMS.V3/build/*.elf
            vehicle/OVMS.V3/build/*.map
          if-no-files-found: warn
