name: Build OVMS Maxus T90 (SoC)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (host)
        uses: actions/checkout@v4

      - name: Build in Espressif container
        uses: addnab/docker-run-action@v3
        with:
          image: espressif/idf:release-v3.3
          options: -v ${{ github.workspace }}:/workspace
          shell: bash
          run: |
            set -e
            cd /workspace/vehicle/OVMS.V3

            echo "🔹 Sourcing ESP-IDF..."
            source ${IDF_PATH}/export.sh

            echo "🔹 Checking for sdkconfig..."
            if [ ! -f sdkconfig ]; then
              if [ -f sdkconfig.default ]; then
                echo "Using sdkconfig.default"
                cp sdkconfig.default sdkconfig
              elif [ -f sdkconfig.minimal ]; then
                echo "Using sdkconfig.minimal"
                cp sdkconfig.minimal sdkconfig
              else
                echo "❌ ERROR: no sdkconfig.default or sdkconfig.minimal found"
                exit 1
              fi
            fi

            echo "🔹 Enabling Maxus T90 module..."
            echo -e '\nCONFIG_OVMS_VEHICLE_MAXUS_T90=y' >> sdkconfig

            echo "🔹 Starting build..."
            make -j4

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ovms3-maxus-t90
          path: |
            vehicle/OVMS.V3/build/ovms3.bin
            vehicle/OVMS.V3/build/partitions.bin
            vehicle/OVMS.V3/build/bootloader/bootloader.bin
            vehicle/OVMS.V3/build/ota_data_initial.bin
