      - name: Build in Espressif container (IDF 5.1)
        uses: addnab/docker-run-action@v3
        with:
          image: espressif/idf:release-v5.1
          options: -v ${{ github.workspace }}:/workspace
          shell: bash
          run: |
            set -e
            cd /workspace/vehicle/OVMS.V3

            echo "🔹 Sourcing ESP-IDF environment..."
            source ${IDF_PATH}/export.sh

            echo "🔹 Resetting sdkconfig..."
            rm -f sdkconfig
            if [ -f sdkconfig.default ]; then
              cp sdkconfig.default sdkconfig
            elif [ -f sdkconfig.minimal ]; then
              cp sdkconfig.minimal sdkconfig
            else
              echo "❌ ERROR: no sdkconfig.default or sdkconfig.minimal found"
              exit 1
            fi

            echo "🔹 Enabling Maxus T90 module..."
            echo "CONFIG_OVMS_VEHICLE_MAXUS_T90=y" >> sdkconfig

            echo "🔹 Enabling FreeRTOS backward compatibility..."
            echo "CONFIG_FREERTOS_ENABLE_BACKWARD_COMPATIBILITY=y" >> sdkconfig

            echo "🔹 Setting target..."
            idf.py set-target esp32

            echo "🔹 Building..."
            idf.py build
